//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.2728.2
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=1.0.2728.2.
// 
namespace Greeting 
{
	using System.Xml.Serialization;
	using System;
	using System.Web.Services.Protocols;
	using System.Web.Services;
    
    
	[System.Web.Services.WebServiceBindingAttribute(Name="GreetingSoap", Namespace="http://www.TomorrowsLearning.com/Greeting")]
	public class Greeting : System.Web.Services.Protocols.SoapHttpClientProtocol 
	{
        
		public Greeting() 
		{
			this.Url = "http://localhost/testbed/chapter10/listing10.6.asmx";
		}
        
		[System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.TomorrowsLearning.com/Greeting/Greet", RequestNamespace="http://www.TomorrowsLearning.com/Greeting", ResponseNamespace="http://www.TomorrowsLearning.com/Greeting", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
		public string Greet(string name) 
		{
			object[] results = this.Invoke("Greet", new object[] {name});
			return ((string)(results[0]));
		}
        
		public System.IAsyncResult BeginGreet(string name, System.AsyncCallback callback, object asyncState) 
		{
			return this.BeginInvoke("Greet", new object[] {name}, callback, asyncState);
		}
        
		public string EndGreet(System.IAsyncResult asyncResult) 
		{
			object[] results = this.EndInvoke(asyncResult);
			return ((string)(results[0]));
		}
	}
}
