<%@ Page %>
<%@ Import Namespace="System.Data"%>
<%@ Import Namespace="System.Data.SqlClient"%>
<%@ Import Namespace="System.Xml"%>
<%@ Import Namespace="System.IO"%>
<script language="C#" runat="server">
    public void Page_Load(Object Src, EventArgs E) { 
        DataSet ds = new DataSet();    

        DataTable tblCustomers = new DataTable("Customers");

        DataColumn customerID = new DataColumn("CustomerID");
        customerID.DataType = System.Type.GetType("System.String");
        customerID.ColumnMapping = MappingType.Attribute;
        customerID.Unique = true;
        tblCustomers.Columns.Add(customerID);
        
        DataColumn companyName = new DataColumn("CompanyName");
        companyName.DataType = System.Type.GetType("System.String");
         companyName.Unique = false;
        tblCustomers.Columns.Add(companyName);
        
        DataColumn contactName = new DataColumn("ContactName");
        contactName.DataType = System.Type.GetType("System.String");
        contactName.Unique = false;
        tblCustomers.Columns.Add(contactName);
        
        DataColumn contactTitle = new DataColumn("ContactTitle");
        contactTitle.DataType = System.Type.GetType("System.String");
        contactTitle.Unique = false;
        tblCustomers.Columns.Add(contactTitle);
        
        ds.Tables.Add(tblCustomers);
        
        DataRow row = ds.Tables["Customers"].NewRow();
        row["CustomerID"] = "DLWID";
        row["CompanyName"] = "Wahlin Consulting";
        row["ContactName"] = "Dan Wahlin";
        row["ContactTitle"] = "Programmer/Author";
        
        //****** Let's see how well the schema validates
        try {
            row["test"] = "Testing Schema";
        }
        catch (Exception exc) {
            //Don't do the insert because column["test"] doesn't really exist
        }
        ds.Tables["Customers"].Rows.Add(row);
        // Code to actually insert the row into a data source would go here.....
        
        BeforeDataGrid.DataSource = ds.Tables["Customers"].DefaultView;
        BeforeDataGrid.DataBind(); 
        xmlText.Value = ds.GetXml();
    }
</script>
<html>
    <body bgcolor="#ffffff">
        <h2>
            Data Loaded into a DataSet and Validated by a Schema
        </h2>
        <ASP:DataGrid id="BeforeDataGrid" runat="server" Width="700" BackColor="#E6E6CC" BorderColor="#000000" ShowFooter="false" CellPadding=5 CellSpacing="0" Font-Name="Arial" Font-Size="8pt" HeaderStyle-BackColor="#6C0A00" HeaderStyle-ForeColor="#ffffff" MaintainState="false" />
        <p>
            <h2>
                XML Generated by DataSet
            </h2>
            <TextArea rows="25" cols="80" id="xmlText" runat="server" NAME="xmlText">
            </TextArea>
    </body>
</html>
